// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ReelRating.Data;

#nullable disable

namespace ReelRating.Data.Migrations
{
    [DbContext(typeof(ReelRatingContext))]
    [Migration("20260629222245_SeedBaseData")]
    partial class SeedBaseData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MOVIEDB")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReelRating.Domain.Entities.AverageHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Hours")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("HOURS");

                    b.Property<int?>("HoursId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("HOURS_ID");

                    b.Property<int?>("Mount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MOUNT");

                    b.HasKey("Id");

                    b.ToTable("AVERAGE_HOURS", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<int?>("TypeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TYPE_ID");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("CATEGORIES", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Cine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Month")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MONTH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NAME");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TMDBID");

                    b.Property<int?>("TypeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TYPE_ID");

                    b.Property<string>("URLPoster")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("URL_POSTER");

                    b.Property<int?>("WhatchId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("WHATCH_ID");

                    b.Property<int?>("Year")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("YEAR");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IDX_CINE_NAME");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasFilter("\"TMDBID\" IS NOT NULL");

                    b.HasIndex("TypeId");

                    b.HasIndex("WhatchId");

                    b.ToTable("CINE", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.CineCategories", b =>
                {
                    b.Property<int>("CineId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CINE_ID");

                    b.Property<int>("CategoriesId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CATEGORIES_ID");

                    b.Property<int?>("CineId1")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CineId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.HasIndex("CineId1");

                    b.ToTable("CINE_CATEGORIES", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CineId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CINE_ID");

                    b.Property<string>("CommentText")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("COMMENT_TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<bool?>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(false)
                        .HasColumnName("DELETED");

                    b.HasKey("Id");

                    b.HasIndex("CineId")
                        .HasDatabaseName("IDX_COMMENT_CINE");

                    b.HasIndex("CustomerId");

                    b.ToTable("COMMENTS", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("CREATEDAT")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NAME");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NICKNAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("PASSWORD");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IDX_CUSTOMER_EMAIL");

                    b.ToTable("CUSTOMER", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.CustomerAverageHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Customer_Id");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("Field");

                    b.Property<int?>("Hours")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Hours");

                    b.HasKey("Id");

                    b.ToTable("Customer_Average_Hours", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.CustomerWhatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<int?>("QttAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("QTT_ACCESS");

                    b.Property<int>("WhatchId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("WHATCH_ID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("WhatchId");

                    b.ToTable("CUSTOMER_WHATCH", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Favorites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CineId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CINE_ID");

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<bool?>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(false)
                        .HasColumnName("DELETED");

                    b.HasKey("Id");

                    b.HasIndex("CineId");

                    b.HasIndex("CustomerId");

                    b.ToTable("FAVORITES", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Notes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CineId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CINE_ID");

                    b.Property<string>("CustomerNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB")
                        .HasColumnName("CUSTOMER_NOTES");

                    b.Property<string>("TMDBNote")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("TMDB_NOTE");

                    b.HasKey("Id");

                    b.HasIndex("CineId");

                    b.ToTable("NOTES", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Preferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriesId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CATEGORIES_ID");

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("NoteOrigin")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOTE_ORIGIN");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PREFERENCES", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriesId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CATEGORIES_ID");

                    b.Property<int>("CineId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CINE_ID");

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<bool?>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(false)
                        .HasColumnName("DELETED");

                    b.Property<int?>("Note")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTE");

                    b.Property<string>("REVIEW")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REVIEW");

                    b.Property<int?>("StatusId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS_ID");

                    b.Property<int?>("TypeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TYPE_ID");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.HasIndex("CineId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("IDX_REVIEW_STATUS");

                    b.HasIndex("TypeId");

                    b.ToTable("REVIEW", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("STATUS", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.TypeCine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("TYPE_CINE", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.WhatchIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(true)
                        .HasColumnName("AVAILABLE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REGION");

                    b.HasKey("Id");

                    b.ToTable("WHATCHIN", "MOVIEDB");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Categories", b =>
                {
                    b.HasOne("ReelRating.Domain.Entities.TypeCine", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_CATEGORY_TYPE");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Cine", b =>
                {
                    b.HasOne("ReelRating.Domain.Entities.TypeCine", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_CINE_TYPE");

                    b.HasOne("ReelRating.Domain.Entities.WhatchIn", null)
                        .WithMany()
                        .HasForeignKey("WhatchId")
                        .HasConstraintName("FK_CINE_WHATCH");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.CineCategories", b =>
                {
                    b.HasOne("ReelRating.Domain.Entities.Categories", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CC_CATEGORY");

                    b.HasOne("ReelRating.Domain.Entities.Cine", null)
                        .WithMany()
                        .HasForeignKey("CineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CC_CINE");

                    b.HasOne("ReelRating.Domain.Entities.Cine", null)
                        .WithMany("CineCategories")
                        .HasForeignKey("CineId1");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Comments", b =>
                {
                    b.HasOne("ReelRating.Domain.Entities.Cine", null)
                        .WithMany()
                        .HasForeignKey("CineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_COMMENTS_CINE");

                    b.HasOne("ReelRating.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_COMMENTS_CUSTOMER");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.CustomerWhatch", b =>
                {
                    b.HasOne("ReelRating.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CW_CUSTOMER");

                    b.HasOne("ReelRating.Domain.Entities.WhatchIn", null)
                        .WithMany()
                        .HasForeignKey("WhatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CW_WHATCH");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Favorites", b =>
                {
                    b.HasOne("ReelRating.Domain.Entities.Cine", null)
                        .WithMany()
                        .HasForeignKey("CineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FAVORITES_CINE");

                    b.HasOne("ReelRating.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FAVORITES_CUSTOMER");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Notes", b =>
                {
                    b.HasOne("ReelRating.Domain.Entities.Cine", null)
                        .WithMany()
                        .HasForeignKey("CineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NOTES_CINE");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Preferences", b =>
                {
                    b.HasOne("ReelRating.Domain.Entities.Categories", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PREF_CATEGORY");

                    b.HasOne("ReelRating.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PREF_CUSTOMER");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Review", b =>
                {
                    b.HasOne("ReelRating.Domain.Entities.Categories", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .HasConstraintName("FK_REVIEW_CATEGORY");

                    b.HasOne("ReelRating.Domain.Entities.Cine", null)
                        .WithMany()
                        .HasForeignKey("CineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REVIEW_CINE");

                    b.HasOne("ReelRating.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REVIEW_CUSTOMER");

                    b.HasOne("ReelRating.Domain.Entities.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_REVIEW_STATUS");

                    b.HasOne("ReelRating.Domain.Entities.TypeCine", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_REVIEW_TYPE");
                });

            modelBuilder.Entity("ReelRating.Domain.Entities.Cine", b =>
                {
                    b.Navigation("CineCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
