services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: oracle_free

    environment:
      - ORACLE_PASSWORD=ReelRatingDB2025
      - ORACLE_CHARACTERSET=AL32UTF8

    ports:
      - "1521:1521"

    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./scripts:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "sqlplus", "-v"]
      interval: 10s
      timeout: 5s
      retries: 30

    restart: unless-stopped

volumes:
  oracle_data:
